time_source_destroy(ts_reset_damage);
time_source_destroy(make_visibile_timer);
time_source_destroy(remove_blinking_timer);
time_source_destroy(remove_blinding_timer);
time_source_destroy(remove_reverse_timer);