enum PacketType {
	CL_PING = 0,
	SV_PONG = 1,
	
	SV_INFO_HOST = 2,
	SV_INFO_CONNECTION_REQUEST = 3,
	SV_INFO_HOST_DISCONNECTED = 4,
	SV_INFO_CLIENT_DISCONNECTED = 5,
	
	CL_REQ_CREATE_LOBBY = 6,
	CL_REQ_JOIN_LOBBY = 7,
	CL_REQ_LOBBY_LIST = 8,
	SV_INFO_LOBBY_CODE = 9,
	SV_INFO_LOBBY_LIST = 10,
	
	HOST_INFO_CONNECTION_ACCEPTED = 11,
	HOST_INFO_CONNECTION_REJECTED = 12,
	
	CL_INFO_PLAYER_NAME = 13,
	HOST_SYNC_PLAYER = 14,
	CL_INFO_PLAYER_POSITION = 15,
	HOST_SYNC_PLAYER_POSITION = 16,
	HOST_SYNC_PLAYER_NAME = 17,
	CL_INFO_PLAYER_STATE = 18,
	HOST_SYNC_PLAYER_STATE = 19,
	CL_REQ_SPELLCAST = 20,
	HOST_SYNC_SPELLCAST = 21,
	CL_REQ_SPELLHIT = 22,
	HOST_SYNC_SPELLHIT = 23
}