enum PacketType {
	CL_PING = 0,
	SV_PONG = 1,
	
	SV_INFO_HOST = 2,
	SV_INFO_CONNECTION_REQUEST = 3,
	SV_INFO_HOST_DISCONNECTED = 4,
	SV_INFO_CLIENT_DISCONNECTED = 5,
	
	CL_REQ_CREATE_LOBBY = 6,
	CL_REQ_JOIN_LOBBY = 7,
	CL_REQ_LOBBY_LIST = 8,
	SV_INFO_LOBBY_CODE = 9,
	SV_INFO_LOBBY_LIST = 10,
	HOST_REQ_REMOVE_FROM_LOBBY = 11,
	
	HOST_INFO_CONNECTION_ACCEPTED = 12,
	HOST_INFO_CONNECTION_REJECTED = 13,
	
	HOST_INFO_CLIENT_DISCONNECTED = 14,
	
	CL_INFO_PLAYER_NAME = 15,
	HOST_SYNC_PLAYER = 16,
	CL_INFO_PLAYER_POSITION = 17,
	HOST_SYNC_PLAYER_POSITION = 18,
	HOST_SYNC_PLAYER_NAME = 19,
	CL_INFO_PLAYER_STATE = 20,
	HOST_SYNC_PLAYER_STATE = 21,
	CL_REQ_SPELLCAST = 22,
	HOST_SYNC_SPELLCAST = 23,
	CL_REQ_SPELLHIT = 24,
	HOST_SYNC_SPELLHIT = 25,
	HOST_SYNC_SPELL_PLATFORM = 26,
	CL_REQ_SPELL_GET = 27,
	HOST_SYNC_SPELL_SLOT = 28,
	HOST_SYNC_PLAYER_HP = 29,
	HOST_SYNC_PLAYER_DIED = 30,
}