enum PacketType {
	CL_PING = 0,
	SV_PONG = 1,
	SV_INFO_HOST = 2,
	SV_INFO_CONNECTION_REQUEST = 3,
	SV_INFO_HOST_DISCONNECTED = 4,
	SV_INFO_CLIENT_DISCONNECTED = 5,
	HOST_INFO_CONNECTION_ACCEPTED = 6,
	CL_INFO_PLAYER_NAME = 7,
	HOST_SYNC_PLAYER = 9,
	CL_INFO_PLAYER_POSITION = 10,
	HOST_SYNC_PLAYER_POSITION = 11,
	HOST_SYNC_PLAYER_NAME = 12,
	CL_INFO_PLAYER_STATE = 13,
	HOST_SYNC_PLAYER_STATE = 14
}